"""Shared configuration for the Dig Ophelia camera processor."""

# --- Tile (fixed hardware unit — keep in sync with ESP32 TILE_ROWS / TILE_COLS) ---
TILE_ROWS = 8
TILE_COLS = 16

# --- Tiles per module (one ESP32) — set to match physical wiring ---
MODULE_TILES_X = 2
MODULE_TILES_Y = 1

# --- Module layout in the install ---
INSTALL_MODULES_X = 1
INSTALL_MODULES_Y = 1

# --- Daisy chain (keep in sync with ESP32 TILE_CHAIN_BLOCK_ORDER) ---
# True: stream bytes tile-by-tile (tile 0 rows 0–7, then tile 1, …).
TILE_CHAIN_BLOCK_ORDER = True

# --- Derived layout (recomputed by recompute_layout()) ---
MODULE_ROWS = 0
MODULE_COLS = 0
MODULE_CELLS = 0
BYTES_PER_MODULE = 0
INSTALL_ROWS = 0
INSTALL_COLS = 0
INSTALL_CELLS = 0
MODULE_COUNT = 0

# Debugger / API aliases (full install grid)
MATRIX_ROWS = 0
MATRIX_COLS = 0

# Processing resolution (recomputed — aspect matches install grid)
PROCESS_BASE_WIDTH = 160
PROCESS_WIDTH = 0
PROCESS_HEIGHT = 0
DEBUG_PREVIEW_WIDTH = 0
DEBUG_PREVIEW_HEIGHT = 0


def recompute_layout() -> None:
    """Recompute derived constants after changing tile/module/install knobs."""
    global MODULE_ROWS, MODULE_COLS, MODULE_CELLS, BYTES_PER_MODULE
    global INSTALL_ROWS, INSTALL_COLS, INSTALL_CELLS, MODULE_COUNT
    global MATRIX_ROWS, MATRIX_COLS
    global PROCESS_WIDTH, PROCESS_HEIGHT, DEBUG_PREVIEW_WIDTH, DEBUG_PREVIEW_HEIGHT

    MODULE_ROWS = TILE_ROWS * MODULE_TILES_Y
    MODULE_COLS = TILE_COLS * MODULE_TILES_X
    MODULE_CELLS = MODULE_ROWS * MODULE_COLS
    BYTES_PER_MODULE = (MODULE_CELLS + 7) // 8

    INSTALL_ROWS = MODULE_ROWS * INSTALL_MODULES_Y
    INSTALL_COLS = MODULE_COLS * INSTALL_MODULES_X
    INSTALL_CELLS = INSTALL_ROWS * INSTALL_COLS
    MODULE_COUNT = INSTALL_MODULES_X * INSTALL_MODULES_Y

    MATRIX_ROWS = INSTALL_ROWS
    MATRIX_COLS = INSTALL_COLS

    PROCESS_WIDTH = PROCESS_BASE_WIDTH
    PROCESS_HEIGHT = max(1, round(PROCESS_BASE_WIDTH * INSTALL_ROWS / INSTALL_COLS))
    DEBUG_PREVIEW_WIDTH = PROCESS_WIDTH
    DEBUG_PREVIEW_HEIGHT = PROCESS_HEIGHT


recompute_layout()

CAMERA_INDEX = 0
CAMERA_WIDTH = 160
CAMERA_HEIGHT = 120
CAMERA_FPS_REQUEST = 30
CAMERA_WARMUP_FRAMES = 10

TARGET_FPS = 25

BG_DIFF_THRESHOLD = 30
BLUR_KERNEL = (5, 5)
INVERT_DETECTION = False
MIRROR_HORIZONTAL = True

MORPHOLOGY_ENABLED = False
MORPH_KERNEL_SIZE = 3
MORPH_OPEN = True
MORPH_CLOSE = True
MIN_CONTOUR_AREA = 50

BACKGROUND_WARMUP_S = 3

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8080

DEBUG_HOST = "0.0.0.0"
DEBUG_PORT = 8080
DEBUG_MJPEG_FPS = 20
DEBUG_JPEG_QUALITY = 30
