"""Shared configuration for the Dig Ophelia camera processor."""

MATRIX_COLS = 16
MATRIX_ROWS = 8
TOTAL_CELLS = MATRIX_COLS * MATRIX_ROWS
BYTES_PER_FRAME = (TOTAL_CELLS + 7) // 8

CAMERA_INDEX = 0
CAMERA_WIDTH = 160
CAMERA_HEIGHT = 120
CAMERA_FPS_REQUEST = 25
CAMERA_WARMUP_FRAMES = 10

PROCESS_WIDTH = CAMERA_WIDTH
PROCESS_HEIGHT = CAMERA_HEIGHT

TARGET_FPS = 20

BG_DIFF_THRESHOLD = 30
BLUR_KERNEL = (5, 5)
INVERT_DETECTION = False
MIRROR_HORIZONTAL = True

MORPHOLOGY_ENABLED = False
MORPH_KERNEL_SIZE = 3
MORPH_OPEN = True
MORPH_CLOSE = True
MIN_CONTOUR_AREA = 50

BACKGROUND_WARMUP_S = 3

DEBUG_HOST = "0.0.0.0"
DEBUG_PORT = 8080
DEBUG_PREVIEW_WIDTH = 160
DEBUG_PREVIEW_HEIGHT = 120
DEBUG_MJPEG_FPS = 20
DEBUG_JPEG_QUALITY = 30
